GET http://localhost:5000/films
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1Njo0Ni4wMDBaIiwiaWF0IjoxNzQ4MTUyNjM2LCJleHAiOjE3NDgxNTI5MzZ9.YC4pD65v2oKXulTbeDg2UT65RN3Rbv86hVzAmBRO2C0
###
GET http://localhost:5000/films/1

###
POST http://localhost:5000/add-film
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1Njo0Ni4wMDBaIiwiaWF0IjoxNzQ4MTUyNjM2LCJleHAiOjE3NDgxNTI5MzZ9.YC4pD65v2oKXulTbeDg2UT65RN3Rbv86hVzAmBRO2C0
Content-Type: application/json

{
    "judul": "Bull eye",
    "genre": "action",
    "tahun": "2123"
}

###
PATCH http://localhost:5000/edit-film/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1Njo0Ni4wMDBaIiwiaWF0IjoxNzQ4MTUyNjM2LCJleHAiOjE3NDgxNTI5MzZ9.YC4pD65v2oKXulTbeDg2UT65RN3Rbv86hVzAmBRO2C0
Content-Type: application/json

{
    "judul": "handuk",
    "genre": "comedy",
    "tahun": "23333"
}

###
DELETE http://localhost:5000/delete-film/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1Njo0Ni4wMDBaIiwiaWF0IjoxNzQ4MTUyNjM2LCJleHAiOjE3NDgxNTI5MzZ9.YC4pD65v2oKXulTbeDg2UT65RN3Rbv86hVzAmBRO2C0

###
GET http://localhost:5000/ratings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1Njo0Ni4wMDBaIiwiaWF0IjoxNzQ4MTUyNjM2LCJleHAiOjE3NDgxNTI5MzZ9.YC4pD65v2oKXulTbeDg2UT65RN3Rbv86hVzAmBRO2C0

###
GET http://localhost:5000/ratings?filmId=1&userId=1

###
POST http://localhost:5000/add-rating
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1Njo0Ni4wMDBaIiwiaWF0IjoxNzQ4MTUyNjM2LCJleHAiOjE3NDgxNTI5MzZ9.YC4pD65v2oKXulTbeDg2UT65RN3Rbv86hVzAmBRO2C0
Content-Type: application/json

{
    "rating": 8,
  "komentar": "Filmnya keren",
  "userId": 1,
  "filmId": 1
}

###
PATCH http://localhost:5000/edit-rating/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1NzoxNi4wMDBaIiwiaWF0IjoxNzQ4MTUzMDMzLCJleHAiOjE3NDgxNTMzMzN9.asmoG0TWHoooeeeQNAtiWuwkOV-ArST1U5NFZUog9Mw
Content-Type: application/json

{
    "rating": "6",
    "komentar": "comedy good"
    
}

###
DELETE http://localhost:5000/delete-rating/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo1NzoxNi4wMDBaIiwiaWF0IjoxNzQ4MTUzMDMzLCJleHAiOjE3NDgxNTMzMzN9.asmoG0TWHoooeeeQNAtiWuwkOV-ArST1U5NFZUog9Mw

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRlc2kiLCJlbWFpbCI6InRlc2lAeWFob28uY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNVQwNTo0NTowMS4wMDBaIiwiaWF0IjoxNzQ4MTUyMjExLCJleHAiOjE3NDgxNTI1MTF9.xpQifcCTwaOvejXOp7voFyXgzKy_W5ryFOLdVxAoehA
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "tesi",
    "email": "tesi@yahoo.com",
    "password": "123456"
}

### 

PUT http://localhost:5000/edit-user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTI1VDAzOjIyOjMzLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI1VDA2OjA2OjIwLjAwMFoiLCJpYXQiOjE3NDgxNTMyMzUsImV4cCI6MTc0ODE1MzUzNX0.pYrm5Qyu70zjIs5iHBxW7-PQRDd1jYO9vnWIeauojyU
Content-Type: application/json

{
    "name": "tessss",
    "email": "tesss@tessss.com",
}

###

DELETE http://localhost:5000/delete-user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTI1VDAzOjIyOjMzLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI1VDA2OjA2OjIwLjAwMFoiLCJpYXQiOjE3NDgxNTMyMzUsImV4cCI6MTc0ODE1MzUzNX0.pYrm5Qyu70zjIs5iHBxW7-PQRDd1jYO9vnWIeauojyU


###

POST http://localhost:5000/login
Content-Type: application/json

{
   
    "name": "tes",
    "password": "12345"
}



###

DELETE http://localhost:5000/logout